name: Deploy preview URL 

on: 
  push:
    branches-ignore:
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v1
        id: deployment_metadata
        with:
          github-token: ${{ secrets.GH_TOKEN}}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}