name: Deploy to production 

on: 
  push:
    tags-ignore:
      - '**'
    branches:
      - master
jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'skip ci') == false 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Semantic release 
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
        run: npx semantic-release
      - name: Deploy to production 
        run: npx now --prod --token=${{ secrets.ZEIT_TOKEN }}
